# version format
version: "{build}"

# branches to build
branches:
  only:
    - master

# Build worker image (VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

environment:
  WeFlowBuild: true
  qiniu_ACCESS_KEY:
      secure: T10k13x11WzEOXvMqo8pXNK4fMb2+iSqj6ate+fhL7pwWxySeKhsoxjZ2GpAAsBU
  qiniu_SECRET_KEY:
      secure: XRWyQSCo7yWHH7LN5AUlFd3UYl/T6ZAc7WiK4NJJGAKocvmEm7ait8jm+y51CZ6c
  matrix:
    - nodejs_version: 5.10.0

matrix:
  fast_finish: true

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - echo "%PLATFORM%"
  - node -v
  - npm -v
  - npm install -g node-gyp
  - npm install
  - ps: Compress-Archive -Path node_modules -DestinationPath dist.zip
#  - cd node_modules\node-lwip
#  - if "%PLATFORM%" == "x64" node-gyp rebuild --target=0.37.8 --arch=x64 --dist-url=https://atom.io/download/atom-shell
#  - if "%PLATFORM%" == "x86" node-gyp rebuild --target=0.37.8 --arch=ia32 --dist-url=https://atom.io/download/atom-shell
#  - cd ..\..\
#  - node build\downBinding
#  - if "%PLATFORM%" == "x64" npm run build:win64
#  - if "%PLATFORM%" == "x86" npm run build:win32
#  - node build\upload


build: OFF
test: OFF
deploy: OFF
