# version format
version: "{build}"

# branches to build
branches:
  only:
    - master

# Build worker image (VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: 5.10.0

matrix:
  fast_finish: true

platform:
  - x86

install:
  - ps: Install-Product node $env:nodejs_version
  - node -v
  - npm -v
  - npm install node-lwip

build: OFF
test: OFF
deploy: OFF