# version format
version: "{build}"

# branches to build
branches:
  only:
    - master

# Build worker image (VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

environment:
  WeFlowBuild: true
  matrix:
    - nodejs_version: 5.10.0

matrix:
  fast_finish: true

platform:
  - x86

install:
  - ps: Install-Product node $env:nodejs_version
  - node -v
  - npm -v
  - npm install -g node-gyp
  - npm install
  - cd C:\projects\weflow\node_modules
  - git clone --recursive https://github.com/sass/node-sass.git
  - cd node-sass
  - git submodule update --init --recursive
  - npm install
  - cd C:\projects\weflow\build
  - node build
#
#  - dir
#  - node-gyp rebuild --target=0.37.8 --arch=x64 --dist-url=https://atom.io/download/atom-shell


build: OFF
test: OFF
deploy: OFF